INSERT INTO `<?php echo $wpdb->prefix;?>mediadb_media` VALUES
	(UUID(),'OftheBlueColouroftheSky.zip','Of the Blue Colour of the Sky - Disc One','extranice-db/extraniceedition/otbcots'),
	(UUID(),'otbcotsLL.zip','Of the Blue Colour of the Sky - Disc One (Lossless)','extranice-db/extraniceedition/otbcots'),
	(UUID(),'otbcotsSecondDisc.zip','Of the Blue Colour of the Sky - Disc Two (MAC)','extranice-db/extraniceedition/otbcots'),
	(UUID(),'otbcotsSecondPC.zip','Of the Blue Colour of the Sky - Disc Two (PC)','extranice-db/extraniceedition/otbcots'),
	(UUID(),'otbcots-track1.zip','Of the Blue Colour of the Sky - Disc Two - Track 1 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track2.zip','Of the Blue Colour of the Sky - Disc Two - Track 2 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track3.zip','Of the Blue Colour of the Sky - Disc Two - Track 3 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track4.zip','Of the Blue Colour of the Sky - Disc Two - Track 4 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track5.zip','Of the Blue Colour of the Sky - Disc Two - Track 5 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track6.zip','Of the Blue Colour of the Sky - Disc Two - Track 6 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track7.zip','Of the Blue Colour of the Sky - Disc Two - Track 7 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track8.zip','Of the Blue Colour of the Sky - Disc Two - Track 8 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track9.zip','Of the Blue Colour of the Sky - Disc Two - Track 9 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track10.zip','Of the Blue Colour of the Sky - Disc Two - Track 10 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track11.zip','Of the Blue Colour of the Sky - Disc Two - Track 11 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track12.zip','Of the Blue Colour of the Sky - Disc Two - Track 12 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track13.zip','Of the Blue Colour of the Sky - Disc Two - Track 13 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track14.zip','Of the Blue Colour of the Sky - Disc Two - Track 14 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track15.zip','Of the Blue Colour of the Sky - Disc Two - Track 15 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track16.zip','Of the Blue Colour of the Sky - Disc Two - Track 16 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track17.zip','Of the Blue Colour of the Sky - Disc Two - Track 17 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track18.zip','Of the Blue Colour of the Sky - Disc Two - Track 18 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track19.zip','Of the Blue Colour of the Sky - Disc Two - Track 19 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track20.zip','Of the Blue Colour of the Sky - Disc Two - Track 20 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track21.zip','Of the Blue Colour of the Sky - Disc Two - Track 21 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'otbcots-track22.zip','Of the Blue Colour of the Sky - Disc Two - Track 22 (Lossless)','extranice-db/extraniceedition/otbcots/tracks'),
	(UUID(),'TwelveRemixesofFourSongs.zip','Twelve Remixes of Four Songs','extranice-db/extraniceedition/trofs'),
	(UUID(),'remixes-track1.zip','Twelve Remixes of Four Songs - Track 1 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track2.zip','Twelve Remixes of Four Songs - Track 2 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track3.zip','Twelve Remixes of Four Songs - Track 3 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track4.zip','Twelve Remixes of Four Songs - Track 4 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track5.zip','Twelve Remixes of Four Songs - Track 5 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track6.zip','Twelve Remixes of Four Songs - Track 6 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track7.zip','Twelve Remixes of Four Songs - Track 7 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track8.zip','Twelve Remixes of Four Songs - Track 8 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track9.zip','Twelve Remixes of Four Songs - Track 9 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track10.zip','Twelve Remixes of Four Songs - Track 10 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track11.zip','Twelve Remixes of Four Songs - Track 11 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'remixes-track12.zip','Twelve Remixes of Four Songs - Track 12 (Lossless)','extranice-db/extraniceedition/trofs/tracks'),
	(UUID(),'OKGoRemixWeek1.zip','Remix Contest Winners - Week 1','extranice-db/extraniceedition/remixContest'),
	(UUID(),'OKGoRemixWeek2.zip','Remix Contest Winners - Week 2','extranice-db/extraniceedition/remixContest'),
	(UUID(),'OKGoRemixWeek3.zip','Remix Contest Winners - Week 3','extranice-db/extraniceedition/remixContest'),
	(UUID(),'OKGoRemixWeek4.zip','Remix Contest Winners - Week 4','extranice-db/extraniceedition/remixContest'),
	(UUID(),'OKGoRemixWeek5.zip','Remix Contest Winners - Week 5','extranice-db/extraniceedition/remixContest');
