INSERT INTO `<?php echo $wpdb->prefix;?>mediadb_media` VALUES
	(UUID(),'OftheBlueColouroftheSky.zip','Of the Blue Colour of the Sky - Disc One'),
	(UUID(),'otbcotsLL.zip','Of the Blue Colour of the Sky - Disc One (Lossless)'),
	(UUID(),'otbcotsSecondDisc.zip','Of the Blue Colour of the Sky - Disc Two (MAC)'),
	(UUID(),'otbcotsSecondPC.zip','Of the Blue Colour of the Sky - Disc Two (PC)'),
	(UUID(),'otbcots-track1.zip','Of the Blue Colour of the Sky - Disc Two - Track 1 (Lossless)'),
	(UUID(),'otbcots-track2.zip','Of the Blue Colour of the Sky - Disc Two - Track 2 (Lossless)'),
	(UUID(),'otbcots-track3.zip','Of the Blue Colour of the Sky - Disc Two - Track 3 (Lossless)'),
	(UUID(),'otbcots-track4.zip','Of the Blue Colour of the Sky - Disc Two - Track 4 (Lossless)'),
	(UUID(),'otbcots-track5.zip','Of the Blue Colour of the Sky - Disc Two - Track 5 (Lossless)'),
	(UUID(),'otbcots-track6.zip','Of the Blue Colour of the Sky - Disc Two - Track 6 (Lossless)'),
	(UUID(),'otbcots-track7.zip','Of the Blue Colour of the Sky - Disc Two - Track 7 (Lossless)'),
	(UUID(),'otbcots-track8.zip','Of the Blue Colour of the Sky - Disc Two - Track 8 (Lossless)'),
	(UUID(),'otbcots-track9.zip','Of the Blue Colour of the Sky - Disc Two - Track 9 (Lossless)'),
	(UUID(),'otbcots-track10.zip','Of the Blue Colour of the Sky - Disc Two - Track 10 (Lossless)'),
	(UUID(),'otbcots-track11.zip','Of the Blue Colour of the Sky - Disc Two - Track 11 (Lossless)'),
	(UUID(),'otbcots-track12.zip','Of the Blue Colour of the Sky - Disc Two - Track 12 (Lossless)'),
	(UUID(),'otbcots-track13.zip','Of the Blue Colour of the Sky - Disc Two - Track 13 (Lossless)'),
	(UUID(),'otbcots-track14.zip','Of the Blue Colour of the Sky - Disc Two - Track 14 (Lossless)'),
	(UUID(),'otbcots-track15.zip','Of the Blue Colour of the Sky - Disc Two - Track 15 (Lossless)'),
	(UUID(),'otbcots-track16.zip','Of the Blue Colour of the Sky - Disc Two - Track 16 (Lossless)'),
	(UUID(),'otbcots-track17.zip','Of the Blue Colour of the Sky - Disc Two - Track 17 (Lossless)'),
	(UUID(),'otbcots-track18.zip','Of the Blue Colour of the Sky - Disc Two - Track 18 (Lossless)'),
	(UUID(),'otbcots-track19.zip','Of the Blue Colour of the Sky - Disc Two - Track 19 (Lossless)'),
	(UUID(),'otbcots-track20.zip','Of the Blue Colour of the Sky - Disc Two - Track 20 (Lossless)'),
	(UUID(),'otbcots-track21.zip','Of the Blue Colour of the Sky - Disc Two - Track 21 (Lossless)'),
	(UUID(),'otbcots-track22.zip','Of the Blue Colour of the Sky - Disc Two - Track 22 (Lossless)'),
	(UUID(),'TwelveRemixesofFourSongs.zip','twelve-remixes">Twelve Remixes of Four Songs'),
	(UUID(),'remixes-track1.zip','Twelve Remixes of Four Songs - Track 1 (Lossless)'),
	(UUID(),'remixes-track2.zip','Twelve Remixes of Four Songs - Track 2 (Lossless)'),
	(UUID(),'remixes-track3.zip','Twelve Remixes of Four Songs - Track 3 (Lossless)'),
	(UUID(),'remixes-track4.zip','Twelve Remixes of Four Songs - Track 4 (Lossless)'),
	(UUID(),'remixes-track5.zip','Twelve Remixes of Four Songs - Track 5 (Lossless)'),
	(UUID(),'remixes-track6.zip','Twelve Remixes of Four Songs - Track 6 (Lossless)'),
	(UUID(),'remixes-track7.zip','Twelve Remixes of Four Songs - Track 7 (Lossless)'),
	(UUID(),'remixes-track8.zip','Twelve Remixes of Four Songs - Track 8 (Lossless)'),
	(UUID(),'remixes-track9.zip','Twelve Remixes of Four Songs - Track 9 (Lossless)'),
	(UUID(),'remixes-track10.zip','Twelve Remixes of Four Songs - Track 10 (Lossless)'),
	(UUID(),'remixes-track11.zip','Twelve Remixes of Four Songs - Track 11 (Lossless)'),
	(UUID(),'remixes-track12.zip','Twelve Remixes of Four Songs - Track 12 (Lossless)'),
	(UUID(),'OkgoRemixWeek1.zip','Remix Contest Winners - Week 1'),
	(UUID(),'OkgoRemixWeek2.zip','Remix Contest Winners - Week 2'),
	(UUID(),'OkgoRemixWeek3.zip','Remix Contest Winners - Week 3'),
	(UUID(),'OkgoRemixWeek4.zip','Remix Contest Winners - Week 4'),
	(UUID(),'OkgoRemixWeek5.zip','Remix Contest Winners - Week 5');
